version: '3'

services:

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    image: php:74
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - ${DOCKER_APP_PORT:-8080}:80
    volumes:
      - .:/var/www/html
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    networks:
     - backend
    ports:
     - ${DOCKER_DB_PORT:-3306}:3306
    volumes:
     - mysql-data:/var/lib/mysql
     - ./docker/mysql/conf.d:/etc/mysql/conf.d

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
